src/Prode/MainBundle/Entity/Forecast.php
<?php

namespace Prode\MainBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Prode\MainBundle\Entity\Forecast
 *
 * @ORM\Table(name="forecast")
 * @ORM\Entity
 */
class Forecast {

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
     * @ORM\ManyToOne(targetEntity="Prode\MainBundle\Entity\Game", inversedBy="forecasts")
     * @ORM\JoinColumn(name="game_id", referencedColumnName="id")
     * */
    private $game;
    
    /**
     * @ORM\ManyToOne(targetEntity="Prode\MainBundle\Entity\User", inversedBy="forecasts")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     * */
    private $user;
    
    /**
     * @ORM\ManyToOne(targetEntity="Prode\MainBundle\Entity\Team")
     * @ORM\JoinColumn(name="result", referencedColumnName="id")
     * */
    private $result;
    
    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    public function __construct($game, $user, $result) {
        $this->game = $game;
        $this->user = $user;
        $this->result = $result;
        $this->date = new \DateTime("now");
    }

    public function getId() {
        return $this->id;
    }

    public function setId($id) {
        $this->id = $id;
    }

    public function getGame() {
        return $this->game;
    }

    public function setGame($game) {
        $this->game = $game;
    }

    public function getUser() {
        return $this->user;
    }

    public function setUser($user) {
        $this->user = $user;
    }

    public function getResult() {
        return $this->result;
    }

    public function setResult($result) {
        $this->result = $result;
    }

    public function getDate() {
        return $this->date;
    }

    public function setDate($date) {
        $this->date = $date;
    }
    
    public function isCorrect() {
        return $this->result->getId() == $this->game->getResult()->getId();
    }
    
    public function isHome() {
        return $this->result->getId() == $this->game->getHome()->getId();
    }
    
    public function isAway() {
        return $this->result->getId() == $this->game->getAway()->getId();
    }
    
    public function isDraw() {
        return $this->result->getId() === 0;
    }
    
    public function __toString() {
        return "Forecast: ".$this->id.". ".$this->game.", Usuario:".$this->user;
    }

}

?>

src/Prode/MainBundle/Resources/views/Admin/editForecasts.html.twig
{% extends 'ProdeMainBundle:Default:baseTwoColumns.html.twig' %}

{% block title %}Editar Prodes{% endblock %}

{% block body %}

<div id="nav-fixture-2-column" style="padding: 5px;">
    
    <h2>Editar {{ editedUser.username }}</h2>
    
    <ul>
        <li class="first">1ra F</li>
        <li class="fechas"><a href="{{ path('edit_forecasts', {'round': 'A', 'userId': editedUser.id}) }}" class="">Grupo A</a></li>
        <li class="fechas"><a href="{{ path('edit_forecasts', {'round': 'B', 'userId': editedUser.id}) }}" class="">Grupo B</a></li>
        <li class="fechas"><a href="{{ path('edit_forecasts', {'round': 'C', 'userId': editedUser.id}) }}" class="">Grupo C</a></li>
        <li class="fechas"><a href="{{ path('edit_forecasts', {'round': 'D', 'userId': editedUser.id}) }}" class="">Grupo D</a></li>
        <li class="fechas"><a href="{{ path('edit_forecasts', {'round': 'E', 'userId': editedUser.id}) }}" class="">Grupo E</a></li>
        <li class="fechas"><a href="{{ path('edit_forecasts', {'round': 'F', 'userId': editedUser.id}) }}" class="">Grupo F</a></li>
        <li class="fechas"><a href="{{ path('edit_forecasts', {'round': 'G', 'userId': editedUser.id}) }}" class="">Grupo G</a></li>
        <li class="fechas"><a href="{{ path('edit_forecasts', {'round': 'H', 'userId': editedUser.id}) }}" class="">Grupo H</a></li>
    </ul>

    <ul>
        <li class="first">2da F</li>
        <li class="fechas"><a href="{{ path('edit_forecasts', {'round': '8', 'userId': editedUser.id}) }}" class="">Octavos</a></li>
        <li class="fechas"><a href="{{ path('edit_forecasts', {'round': '4', 'userId': editedUser.id}) }}" class="">Cuartos</a></li>
        <li class="fechas"><a href="{{ path('edit_forecasts', {'round': '2', 'userId': editedUser.id}) }}" class="">Semi Final</a></li>
        <li class="fechas"><a href="{{ path('edit_forecasts', {'round': '3', 'userId': editedUser.id}) }}" class="">Tercer Puesto</a></li>
        <li class="fechas"><a href="{{ path('edit_forecasts', {'round': '1', 'userId': editedUser.id}) }}" class="">Final</a></li>
    </ul>
</div>

<div id="prode_menu-2-column">
    
    <form class="forecast" method="post">
        <input type="hidden" name="editedUser" value="{{ editedUser.id }}" />
{% for game in games %}
        <div class="prode_content">
            <table class="prode_content" border="0" width="80%" align="center" style="margin: 0px 0px 0px 70px; padding: 0px 0px 0px 0px;">
                <tbody>
                    <tr>
                        <td width="40%" align="left" border="1" valign="middle" style="vertical-align:middle;">
                            <span class="flagsp {{ game.home.img }}" title="{{ game.home.name }}"> </span>
                            <input type="radio" name="games[{{ game.id }}]" value="{{ game.home.id }}" style="vertical-align:middle;" {{ checked[game.id]['home'] }} />
                        </td>
                        <td width="20%" align="center" valign="middle">
                                <input type="radio" name="games[{{ game.id }}]" value="0" style="vertical-align:middle;" {{ checked[game.id]['draw'] }} />
                            </td>
                            <td width="40%" align="right" valign="middle">
                                    <input type="radio" name="games[{{ game.id }}]" value="{{ game.away.id }}" style="vertical-align:middle;" {{ checked[game.id]['away'] }} />
                                    <span class="flagsp {{ game.away.img }}" title="{{ game.away.name }}"> </span>
                                </td>
                            </tr>
                            <tr>	
                                <td class="{{ resultTdClass[game.id]['correct']['home'] }}" width="40%" align="left" valign="middle" style="font-weight: bold;">
                                    <div id="">{{ game.home.name }}</div>
                                </td>
                                <td class="{{ resultTdClass[game.id]['correct']['draw'] }}" width="20%" align="center" valign="middle">
                                    <div id="">Empate</div>
                                </td>
                                <td class="{{ resultTdClass[game.id]['correct']['away'] }}" width="40%" align="right" valign="middle">
                                    <div id="">{{ game.away.name }}</div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="prode_line-2-column"></div>
                </div>
{% endfor %}


                <div id="prode_footer-2-column">
                    <div align="right" style="margin-right: 45px;">
                        <input type="submit" value="Enviar" name="B1" class="button">&nbsp;&nbsp;
                        <input type="reset" value="Borrar" name="B2" class="button">
                    </div>
                </div>

            </form>
        </div>

{% endblock %}

{% block sidebar %}
<h2>Usuarios</h2>
<ul class="sidemenu">
    {% for aUser in users %}
        <li><a href="{{ path('edit_forecasts', {'round': 'A', 'userId': aUser.id}) }}">{{ aUser.username }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

src/Prode/MainBundle/Resources/views/Admin/loadResults.html.twig
{% extends 'ProdeMainBundle:Default:baseOneColumn.html.twig' %}

{% block title %}Cargar Resultados{% endblock %}

{% block body %}

<div id="nav-fixture-2-column" style="padding: 5px;">
    
    <h2>Partidos {{ round }}</h2>
    
    <ul>
        <li class="first">1ra F</li>
        <li class="fechas"><a href="{{ path('load_results', {'round': 'A'}) }}" class="">Grupo A</a></li>
        <li class="fechas"><a href="{{ path('load_results', {'round': 'B'}) }}" class="">Grupo B</a></li>
        <li class="fechas"><a href="{{ path('load_results', {'round': 'C'}) }}" class="">Grupo C</a></li>
        <li class="fechas"><a href="{{ path('load_results', {'round': 'D'}) }}" class="">Grupo D</a></li>
        <li class="fechas"><a href="{{ path('load_results', {'round': 'E'}) }}" class="">Grupo E</a></li>
        <li class="fechas"><a href="{{ path('load_results', {'round': 'F'}) }}" class="">Grupo F</a></li>
        <li class="fechas"><a href="{{ path('load_results', {'round': 'G'}) }}" class="">Grupo G</a></li>
        <li class="fechas"><a href="{{ path('load_results', {'round': 'H'}) }}" class="">Grupo H</a></li>
    </ul>

    <ul>
        <li class="first">2da F</li>
        <li class="fechas"><a href="{{ path('load_results', {'round': '8'}) }}" class="">Octavos</a></li>
        <li class="fechas"><a href="{{ path('load_results', {'round': '4'}) }}" class="">Cuartos</a></li>
        <li class="fechas"><a href="{{ path('load_results', {'round': '2'}) }}" class="">Semi Final</a></li>
        <li class="fechas"><a href="{{ path('load_results', {'round': '3'}) }}" class="">Tercer Puesto</a></li>
        <li class="fechas"><a href="{{ path('load_results', {'round': '1'}) }}" class="">Final</a></li>
    </ul>
</div>

<div id="prode_menu-2-column">
    
    <form class="forecast" method="post">
{% for game in games %}
        <div class="prode_content">
            <table class="prode_content" border="0" width="80%" align="center" style="margin: 0px 0px 0px 70px; padding: 0px 0px 0px 0px;">
                <tbody>
                    <tr>
                        <td width="40%" align="left" border="1" valign="middle" style="vertical-align:middle;">
                            <span class="flagsp {{ game.home.img }}" title="{{ game.home.name }}"> </span>
                            <input type="radio" name="games[{{ game.id }}]" value="{{ game.home.id }}" style="vertical-align:middle;" {{ checked[game.id]['home'] }} />
                        </td>
                        <td width="20%" align="center" valign="middle">
                                <input type="radio" name="games[{{ game.id }}]" value="0" style="vertical-align:middle;" {{ checked[game.id]['draw'] }} />
                            </td>
                            <td width="40%" align="right" valign="middle">
                                    <input type="radio" name="games[{{ game.id }}]" value="{{ game.away.id }}" style="vertical-align:middle;" {{ checked[game.id]['away'] }} />
                                    <span class="flagsp {{ game.away.img }}" title="{{ game.away.name }}"> </span>
                                </td>
                            </tr>
                            <tr>	
                                <td class="{{ resultTdClass[game.id]['checked']['home'] }}" width="40%" align="left" valign="middle" style="font-weight: bold;">
                                    <div id="">{{ game.home.name }}</div>
                                </td>
                                <td class="{{ resultTdClass[game.id]['checked']['draw'] }}" width="20%" align="center" valign="middle">
                                    <div id="">Empate</div>
                                </td>
                                <td class="{{ resultTdClass[game.id]['checked']['away'] }}" width="40%" align="right" valign="middle">
                                    <div id="">{{ game.away.name }}</div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="prode_line-2-column"></div>
                </div>
{% endfor %}


                <div id="prode_footer-2-column">
                    <div align="right" style="margin-right: 45px;">
                        <input type="submit" value="Enviar" name="B1" class="button">&nbsp;&nbsp;
                        <input type="reset" value="Borrar" name="B2" class="button">
                    </div>
                </div>

            </form>
        </div>

{% endblock %}